language: java

jdk:
  - oraclejdk7
  - oraclejdk8

# blacklist 黑名单
branches:
  except:
    - legacy
    - experimental

# whitelist 白名单
branches:
  only:
    - master
    - develop

install:
  - mvn install -Dmaven.test.skip=true

before_script:
  - mvn clean

notifications:
  email:
   recipients:
      - 547933567@qq.com
      - 510647180@qq.com
      - 1243610991@qq.com
<<<<<<< HEAD
    on_success: always
    on_failure: always

deploy:
  provider: releases
  api-key: "ff86d23a5e12841eb1100df0019df738a0b2673b"
  file: "node/data-transfer-excel.xml"
  skip_cleanup: true
  on:
    tags: true
=======
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always
>>>>>>> refs/remotes/origin/develop
