package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsIvmtReserveEntity;

public interface TmsIvmtReserveEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsIvmtReserveEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsIvmtReserveEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsIvmtReserveEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsIvmtReserveEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsIvmtReserveEntity record);
}