package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsIvmtProfitHistEntity;

public interface TmsIvmtProfitHistEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_profit_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_profit_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsIvmtProfitHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_profit_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsIvmtProfitHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_profit_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsIvmtProfitHistEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_profit_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsIvmtProfitHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_profit_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsIvmtProfitHistEntity record);
}