package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsProcProdLogEntity;

public interface TmsProcProdLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_prod_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_prod_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsProcProdLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_prod_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsProcProdLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_prod_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsProcProdLogEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_prod_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsProcProdLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_prod_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsProcProdLogEntity record);
}