package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsProdMastEntity;

public interface TmsProdMastEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsProdMastEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsProdMastEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsProdMastEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsProdMastEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TmsProdMastEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsProdMastEntity record);
}