package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsProdTemplateEntity;

public interface TmsProdTemplateEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsProdTemplateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsProdTemplateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsProdTemplateEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsProdTemplateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TmsProdTemplateEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_template
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsProdTemplateEntity record);
}