package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsIvmtTrsfLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIvmtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_orig_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codOrigProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.dat_trsf
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datTrsf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_proj_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProjUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.amt_per_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtPerUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.ctr_trsf_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrTrsfPortion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.amt_trsf
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtTrsf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.dat_trsf_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datTrsfStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.dat_trsf_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datTrsfEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.amt_priincipal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtPriincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.amt_estimate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtEstimate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.ctr_adjust_ratio
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrAdjustRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.amt_trsf_per
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtTrsfPer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_trsf_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_id
     *
     * @return the value of tms_ivmt_trsf_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_id
     *
     * @param codId the value for tms_ivmt_trsf_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_ivmt_no
     *
     * @return the value of tms_ivmt_trsf_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIvmtNo() {
        return codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_ivmt_no
     *
     * @param codIvmtNo the value for tms_ivmt_trsf_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtNo(String codIvmtNo) {
        this.codIvmtNo = codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_orig_prod_no
     *
     * @return the value of tms_ivmt_trsf_log.cod_orig_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodOrigProdNo() {
        return codOrigProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_orig_prod_no
     *
     * @param codOrigProdNo the value for tms_ivmt_trsf_log.cod_orig_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodOrigProdNo(String codOrigProdNo) {
        this.codOrigProdNo = codOrigProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_prod_no
     *
     * @return the value of tms_ivmt_trsf_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProdNo() {
        return codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_prod_no
     *
     * @param codProdNo the value for tms_ivmt_trsf_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdNo(String codProdNo) {
        this.codProdNo = codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_cust_id
     *
     * @return the value of tms_ivmt_trsf_log.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCustId() {
        return codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_cust_id
     *
     * @param codCustId the value for tms_ivmt_trsf_log.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCustId(String codCustId) {
        this.codCustId = codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_acct_no
     *
     * @return the value of tms_ivmt_trsf_log.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodAcctNo() {
        return codAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_acct_no
     *
     * @param codAcctNo the value for tms_ivmt_trsf_log.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAcctNo(String codAcctNo) {
        this.codAcctNo = codAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.dat_trsf
     *
     * @return the value of tms_ivmt_trsf_log.dat_trsf
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatTrsf() {
        return datTrsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.dat_trsf
     *
     * @param datTrsf the value for tms_ivmt_trsf_log.dat_trsf
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatTrsf(Date datTrsf) {
        this.datTrsf = datTrsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_proj_unit
     *
     * @return the value of tms_ivmt_trsf_log.cod_proj_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProjUnit() {
        return codProjUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_proj_unit
     *
     * @param codProjUnit the value for tms_ivmt_trsf_log.cod_proj_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProjUnit(Integer codProjUnit) {
        this.codProjUnit = codProjUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.amt_per_unit
     *
     * @return the value of tms_ivmt_trsf_log.amt_per_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtPerUnit() {
        return amtPerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.amt_per_unit
     *
     * @param amtPerUnit the value for tms_ivmt_trsf_log.amt_per_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtPerUnit(BigDecimal amtPerUnit) {
        this.amtPerUnit = amtPerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.ctr_trsf_portion
     *
     * @return the value of tms_ivmt_trsf_log.ctr_trsf_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrTrsfPortion() {
        return ctrTrsfPortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.ctr_trsf_portion
     *
     * @param ctrTrsfPortion the value for tms_ivmt_trsf_log.ctr_trsf_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrTrsfPortion(Integer ctrTrsfPortion) {
        this.ctrTrsfPortion = ctrTrsfPortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.amt_trsf
     *
     * @return the value of tms_ivmt_trsf_log.amt_trsf
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtTrsf() {
        return amtTrsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.amt_trsf
     *
     * @param amtTrsf the value for tms_ivmt_trsf_log.amt_trsf
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtTrsf(BigDecimal amtTrsf) {
        this.amtTrsf = amtTrsf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.dat_trsf_start
     *
     * @return the value of tms_ivmt_trsf_log.dat_trsf_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatTrsfStart() {
        return datTrsfStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.dat_trsf_start
     *
     * @param datTrsfStart the value for tms_ivmt_trsf_log.dat_trsf_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatTrsfStart(Date datTrsfStart) {
        this.datTrsfStart = datTrsfStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.dat_trsf_end
     *
     * @return the value of tms_ivmt_trsf_log.dat_trsf_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatTrsfEnd() {
        return datTrsfEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.dat_trsf_end
     *
     * @param datTrsfEnd the value for tms_ivmt_trsf_log.dat_trsf_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatTrsfEnd(Date datTrsfEnd) {
        this.datTrsfEnd = datTrsfEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.amt_priincipal
     *
     * @return the value of tms_ivmt_trsf_log.amt_priincipal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtPriincipal() {
        return amtPriincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.amt_priincipal
     *
     * @param amtPriincipal the value for tms_ivmt_trsf_log.amt_priincipal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtPriincipal(BigDecimal amtPriincipal) {
        this.amtPriincipal = amtPriincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.amt_estimate
     *
     * @return the value of tms_ivmt_trsf_log.amt_estimate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtEstimate() {
        return amtEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.amt_estimate
     *
     * @param amtEstimate the value for tms_ivmt_trsf_log.amt_estimate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtEstimate(BigDecimal amtEstimate) {
        this.amtEstimate = amtEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.ctr_adjust_ratio
     *
     * @return the value of tms_ivmt_trsf_log.ctr_adjust_ratio
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrAdjustRatio() {
        return ctrAdjustRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.ctr_adjust_ratio
     *
     * @param ctrAdjustRatio the value for tms_ivmt_trsf_log.ctr_adjust_ratio
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrAdjustRatio(BigDecimal ctrAdjustRatio) {
        this.ctrAdjustRatio = ctrAdjustRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.amt_trsf_per
     *
     * @return the value of tms_ivmt_trsf_log.amt_trsf_per
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtTrsfPer() {
        return amtTrsfPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.amt_trsf_per
     *
     * @param amtTrsfPer the value for tms_ivmt_trsf_log.amt_trsf_per
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtTrsfPer(BigDecimal amtTrsfPer) {
        this.amtTrsfPer = amtTrsfPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.dat_create
     *
     * @return the value of tms_ivmt_trsf_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.dat_create
     *
     * @param datCreate the value for tms_ivmt_trsf_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_create_user
     *
     * @return the value of tms_ivmt_trsf_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_create_user
     *
     * @param codCreateUser the value for tms_ivmt_trsf_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_create_org
     *
     * @return the value of tms_ivmt_trsf_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_create_org
     *
     * @param codCreateOrg the value for tms_ivmt_trsf_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.dat_modify
     *
     * @return the value of tms_ivmt_trsf_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.dat_modify
     *
     * @param datModify the value for tms_ivmt_trsf_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_modify_user
     *
     * @return the value of tms_ivmt_trsf_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_modify_user
     *
     * @param codModifyUser the value for tms_ivmt_trsf_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.cod_modify_org
     *
     * @return the value of tms_ivmt_trsf_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.cod_modify_org
     *
     * @param codModifyOrg the value for tms_ivmt_trsf_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_trsf_log.ctr_update_srlno
     *
     * @return the value of tms_ivmt_trsf_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_trsf_log.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_ivmt_trsf_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}