package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsIvmtReserveEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_reserve_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codReserveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_prod_category
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_reserve_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codReserveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_reserve_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codReservePortion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.amt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtReserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_min_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrMinProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_max_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrMaxProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_min_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrMinUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_max_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrMaxUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_min_ivmt_amount
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrMinIvmtAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_max_ivmt_amount
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrMaxIvmtAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_start_profit_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date ctrStartProfitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_end_profit_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date ctrEndProfitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_min_balance
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrMinBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_start_reserve_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date ctrStartReserveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_end_reserve_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date ctrEndReserveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_reserve.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_id
     *
     * @return the value of tms_ivmt_reserve.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_id
     *
     * @param codId the value for tms_ivmt_reserve.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_reserve_no
     *
     * @return the value of tms_ivmt_reserve.cod_reserve_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodReserveNo() {
        return codReserveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_reserve_no
     *
     * @param codReserveNo the value for tms_ivmt_reserve.cod_reserve_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodReserveNo(String codReserveNo) {
        this.codReserveNo = codReserveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_cust_id
     *
     * @return the value of tms_ivmt_reserve.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCustId() {
        return codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_cust_id
     *
     * @param codCustId the value for tms_ivmt_reserve.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCustId(String codCustId) {
        this.codCustId = codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_prod_category
     *
     * @return the value of tms_ivmt_reserve.cod_prod_category
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdCategory() {
        return codProdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_prod_category
     *
     * @param codProdCategory the value for tms_ivmt_reserve.cod_prod_category
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdCategory(Integer codProdCategory) {
        this.codProdCategory = codProdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_reserve_type
     *
     * @return the value of tms_ivmt_reserve.cod_reserve_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodReserveType() {
        return codReserveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_reserve_type
     *
     * @param codReserveType the value for tms_ivmt_reserve.cod_reserve_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodReserveType(Integer codReserveType) {
        this.codReserveType = codReserveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_prod_unit
     *
     * @return the value of tms_ivmt_reserve.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdUnit() {
        return codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_prod_unit
     *
     * @param codProdUnit the value for tms_ivmt_reserve.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdUnit(Integer codProdUnit) {
        this.codProdUnit = codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_reserve_portion
     *
     * @return the value of tms_ivmt_reserve.cod_reserve_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodReservePortion() {
        return codReservePortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_reserve_portion
     *
     * @param codReservePortion the value for tms_ivmt_reserve.cod_reserve_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodReservePortion(Integer codReservePortion) {
        this.codReservePortion = codReservePortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.amt_reserve
     *
     * @return the value of tms_ivmt_reserve.amt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtReserve() {
        return amtReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.amt_reserve
     *
     * @param amtReserve the value for tms_ivmt_reserve.amt_reserve
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtReserve(BigDecimal amtReserve) {
        this.amtReserve = amtReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_min_profit
     *
     * @return the value of tms_ivmt_reserve.ctr_min_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrMinProfit() {
        return ctrMinProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_min_profit
     *
     * @param ctrMinProfit the value for tms_ivmt_reserve.ctr_min_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMinProfit(BigDecimal ctrMinProfit) {
        this.ctrMinProfit = ctrMinProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_max_profit
     *
     * @return the value of tms_ivmt_reserve.ctr_max_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrMaxProfit() {
        return ctrMaxProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_max_profit
     *
     * @param ctrMaxProfit the value for tms_ivmt_reserve.ctr_max_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMaxProfit(BigDecimal ctrMaxProfit) {
        this.ctrMaxProfit = ctrMaxProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_min_unit
     *
     * @return the value of tms_ivmt_reserve.ctr_min_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrMinUnit() {
        return ctrMinUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_min_unit
     *
     * @param ctrMinUnit the value for tms_ivmt_reserve.ctr_min_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMinUnit(Integer ctrMinUnit) {
        this.ctrMinUnit = ctrMinUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_max_unit
     *
     * @return the value of tms_ivmt_reserve.ctr_max_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrMaxUnit() {
        return ctrMaxUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_max_unit
     *
     * @param ctrMaxUnit the value for tms_ivmt_reserve.ctr_max_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMaxUnit(Integer ctrMaxUnit) {
        this.ctrMaxUnit = ctrMaxUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_min_ivmt_amount
     *
     * @return the value of tms_ivmt_reserve.ctr_min_ivmt_amount
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrMinIvmtAmount() {
        return ctrMinIvmtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_min_ivmt_amount
     *
     * @param ctrMinIvmtAmount the value for tms_ivmt_reserve.ctr_min_ivmt_amount
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMinIvmtAmount(BigDecimal ctrMinIvmtAmount) {
        this.ctrMinIvmtAmount = ctrMinIvmtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_max_ivmt_amount
     *
     * @return the value of tms_ivmt_reserve.ctr_max_ivmt_amount
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrMaxIvmtAmount() {
        return ctrMaxIvmtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_max_ivmt_amount
     *
     * @param ctrMaxIvmtAmount the value for tms_ivmt_reserve.ctr_max_ivmt_amount
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMaxIvmtAmount(BigDecimal ctrMaxIvmtAmount) {
        this.ctrMaxIvmtAmount = ctrMaxIvmtAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_start_profit_date
     *
     * @return the value of tms_ivmt_reserve.ctr_start_profit_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getCtrStartProfitDate() {
        return ctrStartProfitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_start_profit_date
     *
     * @param ctrStartProfitDate the value for tms_ivmt_reserve.ctr_start_profit_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrStartProfitDate(Date ctrStartProfitDate) {
        this.ctrStartProfitDate = ctrStartProfitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_end_profit_date
     *
     * @return the value of tms_ivmt_reserve.ctr_end_profit_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getCtrEndProfitDate() {
        return ctrEndProfitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_end_profit_date
     *
     * @param ctrEndProfitDate the value for tms_ivmt_reserve.ctr_end_profit_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrEndProfitDate(Date ctrEndProfitDate) {
        this.ctrEndProfitDate = ctrEndProfitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_min_balance
     *
     * @return the value of tms_ivmt_reserve.ctr_min_balance
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrMinBalance() {
        return ctrMinBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_min_balance
     *
     * @param ctrMinBalance the value for tms_ivmt_reserve.ctr_min_balance
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrMinBalance(BigDecimal ctrMinBalance) {
        this.ctrMinBalance = ctrMinBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_start_reserve_date
     *
     * @return the value of tms_ivmt_reserve.ctr_start_reserve_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getCtrStartReserveDate() {
        return ctrStartReserveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_start_reserve_date
     *
     * @param ctrStartReserveDate the value for tms_ivmt_reserve.ctr_start_reserve_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrStartReserveDate(Date ctrStartReserveDate) {
        this.ctrStartReserveDate = ctrStartReserveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_end_reserve_date
     *
     * @return the value of tms_ivmt_reserve.ctr_end_reserve_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getCtrEndReserveDate() {
        return ctrEndReserveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_end_reserve_date
     *
     * @param ctrEndReserveDate the value for tms_ivmt_reserve.ctr_end_reserve_date
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrEndReserveDate(Date ctrEndReserveDate) {
        this.ctrEndReserveDate = ctrEndReserveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.dat_create
     *
     * @return the value of tms_ivmt_reserve.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.dat_create
     *
     * @param datCreate the value for tms_ivmt_reserve.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_create_user
     *
     * @return the value of tms_ivmt_reserve.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_create_user
     *
     * @param codCreateUser the value for tms_ivmt_reserve.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_create_org
     *
     * @return the value of tms_ivmt_reserve.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_create_org
     *
     * @param codCreateOrg the value for tms_ivmt_reserve.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.dat_modify
     *
     * @return the value of tms_ivmt_reserve.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.dat_modify
     *
     * @param datModify the value for tms_ivmt_reserve.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_modify_user
     *
     * @return the value of tms_ivmt_reserve.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_modify_user
     *
     * @param codModifyUser the value for tms_ivmt_reserve.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.cod_modify_org
     *
     * @return the value of tms_ivmt_reserve.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.cod_modify_org
     *
     * @param codModifyOrg the value for tms_ivmt_reserve.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_reserve.ctr_update_srlno
     *
     * @return the value of tms_ivmt_reserve.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_reserve.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_ivmt_reserve.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}