package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsProcSettleLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_process_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProcessNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIvmtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_pending_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codPendingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_cust_id_out
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCustIdOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_acct_no_out
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codAcctNoOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.amt_txn
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtTxn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_cust_id_in
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCustIdIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_acct_no_in
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codAcctNoIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_ref_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codRefNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_proc_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProcStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.txt_message
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.flg_reversal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String flgReversal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.dat_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_settle_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_id
     *
     * @return the value of tms_proc_settle_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_id
     *
     * @param codId the value for tms_proc_settle_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_process_no
     *
     * @return the value of tms_proc_settle_log.cod_process_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProcessNo() {
        return codProcessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_process_no
     *
     * @param codProcessNo the value for tms_proc_settle_log.cod_process_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessNo(String codProcessNo) {
        this.codProcessNo = codProcessNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_prod_no
     *
     * @return the value of tms_proc_settle_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProdNo() {
        return codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_prod_no
     *
     * @param codProdNo the value for tms_proc_settle_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdNo(String codProdNo) {
        this.codProdNo = codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_ivmt_no
     *
     * @return the value of tms_proc_settle_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIvmtNo() {
        return codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_ivmt_no
     *
     * @param codIvmtNo the value for tms_proc_settle_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtNo(String codIvmtNo) {
        this.codIvmtNo = codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_pending_type
     *
     * @return the value of tms_proc_settle_log.cod_pending_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodPendingType() {
        return codPendingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_pending_type
     *
     * @param codPendingType the value for tms_proc_settle_log.cod_pending_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodPendingType(Integer codPendingType) {
        this.codPendingType = codPendingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_cust_id_out
     *
     * @return the value of tms_proc_settle_log.cod_cust_id_out
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCustIdOut() {
        return codCustIdOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_cust_id_out
     *
     * @param codCustIdOut the value for tms_proc_settle_log.cod_cust_id_out
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCustIdOut(String codCustIdOut) {
        this.codCustIdOut = codCustIdOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_acct_no_out
     *
     * @return the value of tms_proc_settle_log.cod_acct_no_out
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodAcctNoOut() {
        return codAcctNoOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_acct_no_out
     *
     * @param codAcctNoOut the value for tms_proc_settle_log.cod_acct_no_out
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAcctNoOut(String codAcctNoOut) {
        this.codAcctNoOut = codAcctNoOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.amt_txn
     *
     * @return the value of tms_proc_settle_log.amt_txn
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtTxn() {
        return amtTxn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.amt_txn
     *
     * @param amtTxn the value for tms_proc_settle_log.amt_txn
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtTxn(BigDecimal amtTxn) {
        this.amtTxn = amtTxn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_cust_id_in
     *
     * @return the value of tms_proc_settle_log.cod_cust_id_in
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCustIdIn() {
        return codCustIdIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_cust_id_in
     *
     * @param codCustIdIn the value for tms_proc_settle_log.cod_cust_id_in
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCustIdIn(String codCustIdIn) {
        this.codCustIdIn = codCustIdIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_acct_no_in
     *
     * @return the value of tms_proc_settle_log.cod_acct_no_in
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodAcctNoIn() {
        return codAcctNoIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_acct_no_in
     *
     * @param codAcctNoIn the value for tms_proc_settle_log.cod_acct_no_in
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAcctNoIn(String codAcctNoIn) {
        this.codAcctNoIn = codAcctNoIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_ref_no
     *
     * @return the value of tms_proc_settle_log.cod_ref_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodRefNo() {
        return codRefNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_ref_no
     *
     * @param codRefNo the value for tms_proc_settle_log.cod_ref_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodRefNo(String codRefNo) {
        this.codRefNo = codRefNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_proc_status
     *
     * @return the value of tms_proc_settle_log.cod_proc_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProcStatus() {
        return codProcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_proc_status
     *
     * @param codProcStatus the value for tms_proc_settle_log.cod_proc_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcStatus(Integer codProcStatus) {
        this.codProcStatus = codProcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.txt_message
     *
     * @return the value of tms_proc_settle_log.txt_message
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtMessage() {
        return txtMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.txt_message
     *
     * @param txtMessage the value for tms_proc_settle_log.txt_message
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtMessage(String txtMessage) {
        this.txtMessage = txtMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.flg_reversal
     *
     * @return the value of tms_proc_settle_log.flg_reversal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getFlgReversal() {
        return flgReversal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.flg_reversal
     *
     * @param flgReversal the value for tms_proc_settle_log.flg_reversal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setFlgReversal(String flgReversal) {
        this.flgReversal = flgReversal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.dat_process
     *
     * @return the value of tms_proc_settle_log.dat_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatProcess() {
        return datProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.dat_process
     *
     * @param datProcess the value for tms_proc_settle_log.dat_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatProcess(Date datProcess) {
        this.datProcess = datProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.dat_create
     *
     * @return the value of tms_proc_settle_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.dat_create
     *
     * @param datCreate the value for tms_proc_settle_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_create_user
     *
     * @return the value of tms_proc_settle_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_create_user
     *
     * @param codCreateUser the value for tms_proc_settle_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_create_org
     *
     * @return the value of tms_proc_settle_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_create_org
     *
     * @param codCreateOrg the value for tms_proc_settle_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.dat_modify
     *
     * @return the value of tms_proc_settle_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.dat_modify
     *
     * @param datModify the value for tms_proc_settle_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_modify_user
     *
     * @return the value of tms_proc_settle_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_modify_user
     *
     * @param codModifyUser the value for tms_proc_settle_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.cod_modify_org
     *
     * @return the value of tms_proc_settle_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.cod_modify_org
     *
     * @param codModifyOrg the value for tms_proc_settle_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_settle_log.ctr_update_srlno
     *
     * @return the value of tms_proc_settle_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_settle_log.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_proc_settle_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}