package com.penging.tms.common.entity;

import java.util.Date;

public class TmsProcClearConfigEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_clear_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codClearNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_table_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_retain_days
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codRetainDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_clear_config.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_id
     *
     * @return the value of tms_proc_clear_config.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_id
     *
     * @param codId the value for tms_proc_clear_config.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_clear_no
     *
     * @return the value of tms_proc_clear_config.cod_clear_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodClearNo() {
        return codClearNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_clear_no
     *
     * @param codClearNo the value for tms_proc_clear_config.cod_clear_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodClearNo(Integer codClearNo) {
        this.codClearNo = codClearNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_table_name
     *
     * @return the value of tms_proc_clear_config.cod_table_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodTableName() {
        return codTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_table_name
     *
     * @param codTableName the value for tms_proc_clear_config.cod_table_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodTableName(String codTableName) {
        this.codTableName = codTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_retain_days
     *
     * @return the value of tms_proc_clear_config.cod_retain_days
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodRetainDays() {
        return codRetainDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_retain_days
     *
     * @param codRetainDays the value for tms_proc_clear_config.cod_retain_days
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodRetainDays(Integer codRetainDays) {
        this.codRetainDays = codRetainDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.dat_create
     *
     * @return the value of tms_proc_clear_config.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.dat_create
     *
     * @param datCreate the value for tms_proc_clear_config.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_create_user
     *
     * @return the value of tms_proc_clear_config.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_create_user
     *
     * @param codCreateUser the value for tms_proc_clear_config.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_create_org
     *
     * @return the value of tms_proc_clear_config.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_create_org
     *
     * @param codCreateOrg the value for tms_proc_clear_config.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.dat_modify
     *
     * @return the value of tms_proc_clear_config.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.dat_modify
     *
     * @param datModify the value for tms_proc_clear_config.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_modify_user
     *
     * @return the value of tms_proc_clear_config.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_modify_user
     *
     * @param codModifyUser the value for tms_proc_clear_config.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.cod_modify_org
     *
     * @return the value of tms_proc_clear_config.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.cod_modify_org
     *
     * @param codModifyOrg the value for tms_proc_clear_config.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_clear_config.ctr_update_srlno
     *
     * @return the value of tms_proc_clear_config.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_clear_config.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_proc_clear_config.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}