package com.penging.tms.common.entity;

import java.util.Date;

public class TmsProcControlEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_process_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProcessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.txt_process_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtProcessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_process_class
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProcessClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_process_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProcessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_process_seq
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProcessSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_process_freq
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProcessFreq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_threads
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codThreads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_handle
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codHandle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_num_commit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codNumCommit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_process_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProcessStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.dat_last_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datLastProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.dat_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.dat_next_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datNextProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_proc_control.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_id
     *
     * @return the value of tms_proc_control.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_id
     *
     * @param codId the value for tms_proc_control.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_process_id
     *
     * @return the value of tms_proc_control.cod_process_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProcessId() {
        return codProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_process_id
     *
     * @param codProcessId the value for tms_proc_control.cod_process_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessId(String codProcessId) {
        this.codProcessId = codProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.txt_process_name
     *
     * @return the value of tms_proc_control.txt_process_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtProcessName() {
        return txtProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.txt_process_name
     *
     * @param txtProcessName the value for tms_proc_control.txt_process_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtProcessName(String txtProcessName) {
        this.txtProcessName = txtProcessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_process_class
     *
     * @return the value of tms_proc_control.cod_process_class
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProcessClass() {
        return codProcessClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_process_class
     *
     * @param codProcessClass the value for tms_proc_control.cod_process_class
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessClass(String codProcessClass) {
        this.codProcessClass = codProcessClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_process_type
     *
     * @return the value of tms_proc_control.cod_process_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProcessType() {
        return codProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_process_type
     *
     * @param codProcessType the value for tms_proc_control.cod_process_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessType(Integer codProcessType) {
        this.codProcessType = codProcessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_process_seq
     *
     * @return the value of tms_proc_control.cod_process_seq
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProcessSeq() {
        return codProcessSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_process_seq
     *
     * @param codProcessSeq the value for tms_proc_control.cod_process_seq
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessSeq(Integer codProcessSeq) {
        this.codProcessSeq = codProcessSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_process_freq
     *
     * @return the value of tms_proc_control.cod_process_freq
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProcessFreq() {
        return codProcessFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_process_freq
     *
     * @param codProcessFreq the value for tms_proc_control.cod_process_freq
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessFreq(Integer codProcessFreq) {
        this.codProcessFreq = codProcessFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_threads
     *
     * @return the value of tms_proc_control.cod_threads
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodThreads() {
        return codThreads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_threads
     *
     * @param codThreads the value for tms_proc_control.cod_threads
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodThreads(Integer codThreads) {
        this.codThreads = codThreads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_handle
     *
     * @return the value of tms_proc_control.cod_handle
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodHandle() {
        return codHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_handle
     *
     * @param codHandle the value for tms_proc_control.cod_handle
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodHandle(Integer codHandle) {
        this.codHandle = codHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_num_commit
     *
     * @return the value of tms_proc_control.cod_num_commit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodNumCommit() {
        return codNumCommit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_num_commit
     *
     * @param codNumCommit the value for tms_proc_control.cod_num_commit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodNumCommit(Integer codNumCommit) {
        this.codNumCommit = codNumCommit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_process_status
     *
     * @return the value of tms_proc_control.cod_process_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProcessStatus() {
        return codProcessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_process_status
     *
     * @param codProcessStatus the value for tms_proc_control.cod_process_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcessStatus(String codProcessStatus) {
        this.codProcessStatus = codProcessStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.dat_last_process
     *
     * @return the value of tms_proc_control.dat_last_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatLastProcess() {
        return datLastProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.dat_last_process
     *
     * @param datLastProcess the value for tms_proc_control.dat_last_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatLastProcess(Date datLastProcess) {
        this.datLastProcess = datLastProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.dat_process
     *
     * @return the value of tms_proc_control.dat_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatProcess() {
        return datProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.dat_process
     *
     * @param datProcess the value for tms_proc_control.dat_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatProcess(Date datProcess) {
        this.datProcess = datProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.dat_next_process
     *
     * @return the value of tms_proc_control.dat_next_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatNextProcess() {
        return datNextProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.dat_next_process
     *
     * @param datNextProcess the value for tms_proc_control.dat_next_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatNextProcess(Date datNextProcess) {
        this.datNextProcess = datNextProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.dat_create
     *
     * @return the value of tms_proc_control.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.dat_create
     *
     * @param datCreate the value for tms_proc_control.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_create_user
     *
     * @return the value of tms_proc_control.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_create_user
     *
     * @param codCreateUser the value for tms_proc_control.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_create_org
     *
     * @return the value of tms_proc_control.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_create_org
     *
     * @param codCreateOrg the value for tms_proc_control.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.dat_modify
     *
     * @return the value of tms_proc_control.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.dat_modify
     *
     * @param datModify the value for tms_proc_control.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_modify_user
     *
     * @return the value of tms_proc_control.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_modify_user
     *
     * @param codModifyUser the value for tms_proc_control.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.cod_modify_org
     *
     * @return the value of tms_proc_control.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.cod_modify_org
     *
     * @param codModifyOrg the value for tms_proc_control.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_proc_control.ctr_update_srlno
     *
     * @return the value of tms_proc_control.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_proc_control.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_proc_control.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}