package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsProdMastLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_template_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codTemplateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_extern_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codExternProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_orig_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codOrigProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIvmtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.txt_prod_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtProdSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_prod
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_prod_rest
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProdRest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_per_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtPerUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_number_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codNumberUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_rest_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdRestUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_prod_break
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProdBreak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_currency
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProdCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_category
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_support
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdSupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_holder_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codHolderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.txt_holder_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtHolderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_plan_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datPlanStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_plan_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datPlanEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_acctual_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datAcctualStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_acctual_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datAcctualEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_prod_search_term
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdSearchTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_stop_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codStopType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.txt_tag
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_proc_mantissa
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProcMantissa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.flg_transfer_allow
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String flgTransferAllow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_coupon_allow
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codCouponAllow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.ctr_trsf_ratio_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrTrsfRatioMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.ctr_trsf_ratio_min
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrTrsfRatioMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.ctr_ratio_min_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrRatioMinLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.ctr_ratio_max_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrRatioMaxLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_ivmt_min
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtIvmtMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_ivmt_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtIvmtMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_reserve_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datReserveStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_reserve_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datReserveEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_reserve_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtReserveMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_reserve_cust_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtReserveCustLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_auto_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datAutoStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_auto_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datAutoEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_vip_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datVipStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_vip_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datVipEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_vip_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtVipMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_vip_cust_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtVipCustLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_trsf_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datTrsfStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_trsf_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datTrsfEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_apply_user_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codApplyUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.flg_specify_users
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String flgSpecifyUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_show
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_annual_rate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal codAnnualRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_prod_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProdProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_prod_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProdCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_comp_today
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codCompToday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_comp_totally
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codCompTotally;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_last_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datLastProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_next_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datNextProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_last_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datLastCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_next_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datNextCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.flg_principalization
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String flgPrincipalization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.amt_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtAdjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_adjust_ratio
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal codAdjustRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_break_hold_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codBreakHoldNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_acct_guarantee
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codAcctGuarantee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.cod_profit_method
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProfitMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.txt_specify_users
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtSpecifyUsers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_prod_mast_log.txt_prod_info
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtProdInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_id
     *
     * @return the value of tms_prod_mast_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_id
     *
     * @param codId the value for tms_prod_mast_log.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_no
     *
     * @return the value of tms_prod_mast_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProdNo() {
        return codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_no
     *
     * @param codProdNo the value for tms_prod_mast_log.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdNo(String codProdNo) {
        this.codProdNo = codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_template_no
     *
     * @return the value of tms_prod_mast_log.cod_template_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodTemplateNo() {
        return codTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_template_no
     *
     * @param codTemplateNo the value for tms_prod_mast_log.cod_template_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodTemplateNo(String codTemplateNo) {
        this.codTemplateNo = codTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_extern_prod_no
     *
     * @return the value of tms_prod_mast_log.cod_extern_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodExternProdNo() {
        return codExternProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_extern_prod_no
     *
     * @param codExternProdNo the value for tms_prod_mast_log.cod_extern_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodExternProdNo(String codExternProdNo) {
        this.codExternProdNo = codExternProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_orig_prod_no
     *
     * @return the value of tms_prod_mast_log.cod_orig_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodOrigProdNo() {
        return codOrigProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_orig_prod_no
     *
     * @param codOrigProdNo the value for tms_prod_mast_log.cod_orig_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodOrigProdNo(String codOrigProdNo) {
        this.codOrigProdNo = codOrigProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_ivmt_no
     *
     * @return the value of tms_prod_mast_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIvmtNo() {
        return codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_ivmt_no
     *
     * @param codIvmtNo the value for tms_prod_mast_log.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtNo(String codIvmtNo) {
        this.codIvmtNo = codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.txt_prod_source
     *
     * @return the value of tms_prod_mast_log.txt_prod_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtProdSource() {
        return txtProdSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.txt_prod_source
     *
     * @param txtProdSource the value for tms_prod_mast_log.txt_prod_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtProdSource(String txtProdSource) {
        this.txtProdSource = txtProdSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_unit
     *
     * @return the value of tms_prod_mast_log.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdUnit() {
        return codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_unit
     *
     * @param codProdUnit the value for tms_prod_mast_log.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdUnit(Integer codProdUnit) {
        this.codProdUnit = codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_prod
     *
     * @return the value of tms_prod_mast_log.amt_prod
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProd() {
        return amtProd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_prod
     *
     * @param amtProd the value for tms_prod_mast_log.amt_prod
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProd(BigDecimal amtProd) {
        this.amtProd = amtProd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_prod_rest
     *
     * @return the value of tms_prod_mast_log.amt_prod_rest
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProdRest() {
        return amtProdRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_prod_rest
     *
     * @param amtProdRest the value for tms_prod_mast_log.amt_prod_rest
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProdRest(BigDecimal amtProdRest) {
        this.amtProdRest = amtProdRest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_per_unit
     *
     * @return the value of tms_prod_mast_log.amt_per_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtPerUnit() {
        return amtPerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_per_unit
     *
     * @param amtPerUnit the value for tms_prod_mast_log.amt_per_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtPerUnit(BigDecimal amtPerUnit) {
        this.amtPerUnit = amtPerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_number_unit
     *
     * @return the value of tms_prod_mast_log.cod_number_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodNumberUnit() {
        return codNumberUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_number_unit
     *
     * @param codNumberUnit the value for tms_prod_mast_log.cod_number_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodNumberUnit(Integer codNumberUnit) {
        this.codNumberUnit = codNumberUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_rest_unit
     *
     * @return the value of tms_prod_mast_log.cod_prod_rest_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdRestUnit() {
        return codProdRestUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_rest_unit
     *
     * @param codProdRestUnit the value for tms_prod_mast_log.cod_prod_rest_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdRestUnit(Integer codProdRestUnit) {
        this.codProdRestUnit = codProdRestUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_prod_break
     *
     * @return the value of tms_prod_mast_log.amt_prod_break
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProdBreak() {
        return amtProdBreak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_prod_break
     *
     * @param amtProdBreak the value for tms_prod_mast_log.amt_prod_break
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProdBreak(BigDecimal amtProdBreak) {
        this.amtProdBreak = amtProdBreak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_currency
     *
     * @return the value of tms_prod_mast_log.cod_prod_currency
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProdCurrency() {
        return codProdCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_currency
     *
     * @param codProdCurrency the value for tms_prod_mast_log.cod_prod_currency
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdCurrency(String codProdCurrency) {
        this.codProdCurrency = codProdCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_category
     *
     * @return the value of tms_prod_mast_log.cod_prod_category
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdCategory() {
        return codProdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_category
     *
     * @param codProdCategory the value for tms_prod_mast_log.cod_prod_category
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdCategory(Integer codProdCategory) {
        this.codProdCategory = codProdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_status
     *
     * @return the value of tms_prod_mast_log.cod_prod_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdStatus() {
        return codProdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_status
     *
     * @param codProdStatus the value for tms_prod_mast_log.cod_prod_status
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdStatus(Integer codProdStatus) {
        this.codProdStatus = codProdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_support
     *
     * @return the value of tms_prod_mast_log.cod_prod_support
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdSupport() {
        return codProdSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_support
     *
     * @param codProdSupport the value for tms_prod_mast_log.cod_prod_support
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdSupport(Integer codProdSupport) {
        this.codProdSupport = codProdSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_holder_no
     *
     * @return the value of tms_prod_mast_log.cod_holder_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodHolderNo() {
        return codHolderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_holder_no
     *
     * @param codHolderNo the value for tms_prod_mast_log.cod_holder_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodHolderNo(String codHolderNo) {
        this.codHolderNo = codHolderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.txt_holder_name
     *
     * @return the value of tms_prod_mast_log.txt_holder_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtHolderName() {
        return txtHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.txt_holder_name
     *
     * @param txtHolderName the value for tms_prod_mast_log.txt_holder_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtHolderName(String txtHolderName) {
        this.txtHolderName = txtHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_plan_start
     *
     * @return the value of tms_prod_mast_log.dat_plan_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatPlanStart() {
        return datPlanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_plan_start
     *
     * @param datPlanStart the value for tms_prod_mast_log.dat_plan_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatPlanStart(Date datPlanStart) {
        this.datPlanStart = datPlanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_plan_end
     *
     * @return the value of tms_prod_mast_log.dat_plan_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatPlanEnd() {
        return datPlanEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_plan_end
     *
     * @param datPlanEnd the value for tms_prod_mast_log.dat_plan_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatPlanEnd(Date datPlanEnd) {
        this.datPlanEnd = datPlanEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_acctual_start
     *
     * @return the value of tms_prod_mast_log.dat_acctual_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatAcctualStart() {
        return datAcctualStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_acctual_start
     *
     * @param datAcctualStart the value for tms_prod_mast_log.dat_acctual_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatAcctualStart(Date datAcctualStart) {
        this.datAcctualStart = datAcctualStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_acctual_end
     *
     * @return the value of tms_prod_mast_log.dat_acctual_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatAcctualEnd() {
        return datAcctualEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_acctual_end
     *
     * @param datAcctualEnd the value for tms_prod_mast_log.dat_acctual_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatAcctualEnd(Date datAcctualEnd) {
        this.datAcctualEnd = datAcctualEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_prod_search_term
     *
     * @return the value of tms_prod_mast_log.cod_prod_search_term
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdSearchTerm() {
        return codProdSearchTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_prod_search_term
     *
     * @param codProdSearchTerm the value for tms_prod_mast_log.cod_prod_search_term
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdSearchTerm(Integer codProdSearchTerm) {
        this.codProdSearchTerm = codProdSearchTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_stop_type
     *
     * @return the value of tms_prod_mast_log.cod_stop_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodStopType() {
        return codStopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_stop_type
     *
     * @param codStopType the value for tms_prod_mast_log.cod_stop_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodStopType(Integer codStopType) {
        this.codStopType = codStopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.txt_tag
     *
     * @return the value of tms_prod_mast_log.txt_tag
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtTag() {
        return txtTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.txt_tag
     *
     * @param txtTag the value for tms_prod_mast_log.txt_tag
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtTag(String txtTag) {
        this.txtTag = txtTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_proc_mantissa
     *
     * @return the value of tms_prod_mast_log.cod_proc_mantissa
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProcMantissa() {
        return codProcMantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_proc_mantissa
     *
     * @param codProcMantissa the value for tms_prod_mast_log.cod_proc_mantissa
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProcMantissa(Integer codProcMantissa) {
        this.codProcMantissa = codProcMantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.flg_transfer_allow
     *
     * @return the value of tms_prod_mast_log.flg_transfer_allow
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getFlgTransferAllow() {
        return flgTransferAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.flg_transfer_allow
     *
     * @param flgTransferAllow the value for tms_prod_mast_log.flg_transfer_allow
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setFlgTransferAllow(String flgTransferAllow) {
        this.flgTransferAllow = flgTransferAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_coupon_allow
     *
     * @return the value of tms_prod_mast_log.cod_coupon_allow
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodCouponAllow() {
        return codCouponAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_coupon_allow
     *
     * @param codCouponAllow the value for tms_prod_mast_log.cod_coupon_allow
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCouponAllow(Integer codCouponAllow) {
        this.codCouponAllow = codCouponAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.ctr_trsf_ratio_max
     *
     * @return the value of tms_prod_mast_log.ctr_trsf_ratio_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrTrsfRatioMax() {
        return ctrTrsfRatioMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.ctr_trsf_ratio_max
     *
     * @param ctrTrsfRatioMax the value for tms_prod_mast_log.ctr_trsf_ratio_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrTrsfRatioMax(BigDecimal ctrTrsfRatioMax) {
        this.ctrTrsfRatioMax = ctrTrsfRatioMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.ctr_trsf_ratio_min
     *
     * @return the value of tms_prod_mast_log.ctr_trsf_ratio_min
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrTrsfRatioMin() {
        return ctrTrsfRatioMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.ctr_trsf_ratio_min
     *
     * @param ctrTrsfRatioMin the value for tms_prod_mast_log.ctr_trsf_ratio_min
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrTrsfRatioMin(BigDecimal ctrTrsfRatioMin) {
        this.ctrTrsfRatioMin = ctrTrsfRatioMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.ctr_ratio_min_limit
     *
     * @return the value of tms_prod_mast_log.ctr_ratio_min_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrRatioMinLimit() {
        return ctrRatioMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.ctr_ratio_min_limit
     *
     * @param ctrRatioMinLimit the value for tms_prod_mast_log.ctr_ratio_min_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrRatioMinLimit(BigDecimal ctrRatioMinLimit) {
        this.ctrRatioMinLimit = ctrRatioMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.ctr_ratio_max_limit
     *
     * @return the value of tms_prod_mast_log.ctr_ratio_max_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrRatioMaxLimit() {
        return ctrRatioMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.ctr_ratio_max_limit
     *
     * @param ctrRatioMaxLimit the value for tms_prod_mast_log.ctr_ratio_max_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrRatioMaxLimit(BigDecimal ctrRatioMaxLimit) {
        this.ctrRatioMaxLimit = ctrRatioMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_ivmt_min
     *
     * @return the value of tms_prod_mast_log.amt_ivmt_min
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtIvmtMin() {
        return amtIvmtMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_ivmt_min
     *
     * @param amtIvmtMin the value for tms_prod_mast_log.amt_ivmt_min
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtIvmtMin(BigDecimal amtIvmtMin) {
        this.amtIvmtMin = amtIvmtMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_ivmt_max
     *
     * @return the value of tms_prod_mast_log.amt_ivmt_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtIvmtMax() {
        return amtIvmtMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_ivmt_max
     *
     * @param amtIvmtMax the value for tms_prod_mast_log.amt_ivmt_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtIvmtMax(BigDecimal amtIvmtMax) {
        this.amtIvmtMax = amtIvmtMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_reserve_start
     *
     * @return the value of tms_prod_mast_log.dat_reserve_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatReserveStart() {
        return datReserveStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_reserve_start
     *
     * @param datReserveStart the value for tms_prod_mast_log.dat_reserve_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatReserveStart(Date datReserveStart) {
        this.datReserveStart = datReserveStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_reserve_end
     *
     * @return the value of tms_prod_mast_log.dat_reserve_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatReserveEnd() {
        return datReserveEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_reserve_end
     *
     * @param datReserveEnd the value for tms_prod_mast_log.dat_reserve_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatReserveEnd(Date datReserveEnd) {
        this.datReserveEnd = datReserveEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_reserve_max
     *
     * @return the value of tms_prod_mast_log.amt_reserve_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtReserveMax() {
        return amtReserveMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_reserve_max
     *
     * @param amtReserveMax the value for tms_prod_mast_log.amt_reserve_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtReserveMax(BigDecimal amtReserveMax) {
        this.amtReserveMax = amtReserveMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_reserve_cust_limit
     *
     * @return the value of tms_prod_mast_log.amt_reserve_cust_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtReserveCustLimit() {
        return amtReserveCustLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_reserve_cust_limit
     *
     * @param amtReserveCustLimit the value for tms_prod_mast_log.amt_reserve_cust_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtReserveCustLimit(BigDecimal amtReserveCustLimit) {
        this.amtReserveCustLimit = amtReserveCustLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_auto_start
     *
     * @return the value of tms_prod_mast_log.dat_auto_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatAutoStart() {
        return datAutoStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_auto_start
     *
     * @param datAutoStart the value for tms_prod_mast_log.dat_auto_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatAutoStart(Date datAutoStart) {
        this.datAutoStart = datAutoStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_auto_end
     *
     * @return the value of tms_prod_mast_log.dat_auto_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatAutoEnd() {
        return datAutoEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_auto_end
     *
     * @param datAutoEnd the value for tms_prod_mast_log.dat_auto_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatAutoEnd(Date datAutoEnd) {
        this.datAutoEnd = datAutoEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_vip_start
     *
     * @return the value of tms_prod_mast_log.dat_vip_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatVipStart() {
        return datVipStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_vip_start
     *
     * @param datVipStart the value for tms_prod_mast_log.dat_vip_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatVipStart(Date datVipStart) {
        this.datVipStart = datVipStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_vip_end
     *
     * @return the value of tms_prod_mast_log.dat_vip_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatVipEnd() {
        return datVipEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_vip_end
     *
     * @param datVipEnd the value for tms_prod_mast_log.dat_vip_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatVipEnd(Date datVipEnd) {
        this.datVipEnd = datVipEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_vip_max
     *
     * @return the value of tms_prod_mast_log.amt_vip_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtVipMax() {
        return amtVipMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_vip_max
     *
     * @param amtVipMax the value for tms_prod_mast_log.amt_vip_max
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtVipMax(BigDecimal amtVipMax) {
        this.amtVipMax = amtVipMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_vip_cust_limit
     *
     * @return the value of tms_prod_mast_log.amt_vip_cust_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtVipCustLimit() {
        return amtVipCustLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_vip_cust_limit
     *
     * @param amtVipCustLimit the value for tms_prod_mast_log.amt_vip_cust_limit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtVipCustLimit(BigDecimal amtVipCustLimit) {
        this.amtVipCustLimit = amtVipCustLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_trsf_start
     *
     * @return the value of tms_prod_mast_log.dat_trsf_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatTrsfStart() {
        return datTrsfStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_trsf_start
     *
     * @param datTrsfStart the value for tms_prod_mast_log.dat_trsf_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatTrsfStart(Date datTrsfStart) {
        this.datTrsfStart = datTrsfStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_trsf_end
     *
     * @return the value of tms_prod_mast_log.dat_trsf_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatTrsfEnd() {
        return datTrsfEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_trsf_end
     *
     * @param datTrsfEnd the value for tms_prod_mast_log.dat_trsf_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatTrsfEnd(Date datTrsfEnd) {
        this.datTrsfEnd = datTrsfEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_apply_user_type
     *
     * @return the value of tms_prod_mast_log.cod_apply_user_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodApplyUserType() {
        return codApplyUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_apply_user_type
     *
     * @param codApplyUserType the value for tms_prod_mast_log.cod_apply_user_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodApplyUserType(Integer codApplyUserType) {
        this.codApplyUserType = codApplyUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.flg_specify_users
     *
     * @return the value of tms_prod_mast_log.flg_specify_users
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getFlgSpecifyUsers() {
        return flgSpecifyUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.flg_specify_users
     *
     * @param flgSpecifyUsers the value for tms_prod_mast_log.flg_specify_users
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setFlgSpecifyUsers(String flgSpecifyUsers) {
        this.flgSpecifyUsers = flgSpecifyUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_show
     *
     * @return the value of tms_prod_mast_log.dat_show
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatShow() {
        return datShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_show
     *
     * @param datShow the value for tms_prod_mast_log.dat_show
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatShow(Date datShow) {
        this.datShow = datShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_annual_rate
     *
     * @return the value of tms_prod_mast_log.cod_annual_rate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCodAnnualRate() {
        return codAnnualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_annual_rate
     *
     * @param codAnnualRate the value for tms_prod_mast_log.cod_annual_rate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAnnualRate(BigDecimal codAnnualRate) {
        this.codAnnualRate = codAnnualRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_prod_profit
     *
     * @return the value of tms_prod_mast_log.amt_prod_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProdProfit() {
        return amtProdProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_prod_profit
     *
     * @param amtProdProfit the value for tms_prod_mast_log.amt_prod_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProdProfit(BigDecimal amtProdProfit) {
        this.amtProdProfit = amtProdProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_prod_charge
     *
     * @return the value of tms_prod_mast_log.amt_prod_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProdCharge() {
        return amtProdCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_prod_charge
     *
     * @param amtProdCharge the value for tms_prod_mast_log.amt_prod_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProdCharge(BigDecimal amtProdCharge) {
        this.amtProdCharge = amtProdCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_comp_today
     *
     * @return the value of tms_prod_mast_log.cod_comp_today
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodCompToday() {
        return codCompToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_comp_today
     *
     * @param codCompToday the value for tms_prod_mast_log.cod_comp_today
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCompToday(Integer codCompToday) {
        this.codCompToday = codCompToday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_comp_totally
     *
     * @return the value of tms_prod_mast_log.cod_comp_totally
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodCompTotally() {
        return codCompTotally;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_comp_totally
     *
     * @param codCompTotally the value for tms_prod_mast_log.cod_comp_totally
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCompTotally(Integer codCompTotally) {
        this.codCompTotally = codCompTotally;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_last_process
     *
     * @return the value of tms_prod_mast_log.dat_last_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatLastProcess() {
        return datLastProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_last_process
     *
     * @param datLastProcess the value for tms_prod_mast_log.dat_last_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatLastProcess(Date datLastProcess) {
        this.datLastProcess = datLastProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_next_process
     *
     * @return the value of tms_prod_mast_log.dat_next_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatNextProcess() {
        return datNextProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_next_process
     *
     * @param datNextProcess the value for tms_prod_mast_log.dat_next_process
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatNextProcess(Date datNextProcess) {
        this.datNextProcess = datNextProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_last_charge
     *
     * @return the value of tms_prod_mast_log.dat_last_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatLastCharge() {
        return datLastCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_last_charge
     *
     * @param datLastCharge the value for tms_prod_mast_log.dat_last_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatLastCharge(Date datLastCharge) {
        this.datLastCharge = datLastCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_next_charge
     *
     * @return the value of tms_prod_mast_log.dat_next_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatNextCharge() {
        return datNextCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_next_charge
     *
     * @param datNextCharge the value for tms_prod_mast_log.dat_next_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatNextCharge(Date datNextCharge) {
        this.datNextCharge = datNextCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.flg_principalization
     *
     * @return the value of tms_prod_mast_log.flg_principalization
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getFlgPrincipalization() {
        return flgPrincipalization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.flg_principalization
     *
     * @param flgPrincipalization the value for tms_prod_mast_log.flg_principalization
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setFlgPrincipalization(String flgPrincipalization) {
        this.flgPrincipalization = flgPrincipalization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_create
     *
     * @return the value of tms_prod_mast_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_create
     *
     * @param datCreate the value for tms_prod_mast_log.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_create_user
     *
     * @return the value of tms_prod_mast_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_create_user
     *
     * @param codCreateUser the value for tms_prod_mast_log.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_create_org
     *
     * @return the value of tms_prod_mast_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_create_org
     *
     * @param codCreateOrg the value for tms_prod_mast_log.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.dat_modify
     *
     * @return the value of tms_prod_mast_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.dat_modify
     *
     * @param datModify the value for tms_prod_mast_log.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_modify_user
     *
     * @return the value of tms_prod_mast_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_modify_user
     *
     * @param codModifyUser the value for tms_prod_mast_log.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_modify_org
     *
     * @return the value of tms_prod_mast_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_modify_org
     *
     * @param codModifyOrg the value for tms_prod_mast_log.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.ctr_update_srlno
     *
     * @return the value of tms_prod_mast_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_prod_mast_log.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.amt_adjust
     *
     * @return the value of tms_prod_mast_log.amt_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtAdjust() {
        return amtAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.amt_adjust
     *
     * @param amtAdjust the value for tms_prod_mast_log.amt_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtAdjust(BigDecimal amtAdjust) {
        this.amtAdjust = amtAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_adjust_ratio
     *
     * @return the value of tms_prod_mast_log.cod_adjust_ratio
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCodAdjustRatio() {
        return codAdjustRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_adjust_ratio
     *
     * @param codAdjustRatio the value for tms_prod_mast_log.cod_adjust_ratio
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAdjustRatio(BigDecimal codAdjustRatio) {
        this.codAdjustRatio = codAdjustRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_break_hold_no
     *
     * @return the value of tms_prod_mast_log.cod_break_hold_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodBreakHoldNo() {
        return codBreakHoldNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_break_hold_no
     *
     * @param codBreakHoldNo the value for tms_prod_mast_log.cod_break_hold_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodBreakHoldNo(String codBreakHoldNo) {
        this.codBreakHoldNo = codBreakHoldNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_acct_guarantee
     *
     * @return the value of tms_prod_mast_log.cod_acct_guarantee
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodAcctGuarantee() {
        return codAcctGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_acct_guarantee
     *
     * @param codAcctGuarantee the value for tms_prod_mast_log.cod_acct_guarantee
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAcctGuarantee(String codAcctGuarantee) {
        this.codAcctGuarantee = codAcctGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.cod_profit_method
     *
     * @return the value of tms_prod_mast_log.cod_profit_method
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProfitMethod() {
        return codProfitMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.cod_profit_method
     *
     * @param codProfitMethod the value for tms_prod_mast_log.cod_profit_method
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProfitMethod(Integer codProfitMethod) {
        this.codProfitMethod = codProfitMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.txt_specify_users
     *
     * @return the value of tms_prod_mast_log.txt_specify_users
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtSpecifyUsers() {
        return txtSpecifyUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.txt_specify_users
     *
     * @param txtSpecifyUsers the value for tms_prod_mast_log.txt_specify_users
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtSpecifyUsers(String txtSpecifyUsers) {
        this.txtSpecifyUsers = txtSpecifyUsers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_prod_mast_log.txt_prod_info
     *
     * @return the value of tms_prod_mast_log.txt_prod_info
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtProdInfo() {
        return txtProdInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_prod_mast_log.txt_prod_info
     *
     * @param txtProdInfo the value for tms_prod_mast_log.txt_prod_info
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtProdInfo(String txtProdInfo) {
        this.txtProdInfo = txtProdInfo;
    }
}