package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsIvmtTrsfLogEntity;

public interface TmsIvmtTrsfLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_trsf_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_trsf_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsIvmtTrsfLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_trsf_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsIvmtTrsfLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_trsf_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsIvmtTrsfLogEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_trsf_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsIvmtTrsfLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_ivmt_trsf_log
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsIvmtTrsfLogEntity record);
}