package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsProcControlEntity;

public interface TmsProcControlEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_control
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_control
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsProcControlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_control
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsProcControlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_control
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsProcControlEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_control
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsProcControlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_proc_control
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsProcControlEntity record);
}