package com.penging.tms.common.repository;

import com.penging.tms.common.entity.TmsProdMastHistEntity;

public interface TmsProdMastHistEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int deleteByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insert(TmsProdMastHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int insertSelective(TmsProdMastHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    TmsProdMastHistEntity selectByPrimaryKey(Long codId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeySelective(TmsProdMastHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TmsProdMastHistEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tms_prod_mast_hist
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    int updateByPrimaryKey(TmsProdMastHistEntity record);
}