package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsIvmtAmountXrefEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIvmtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_coupon_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codCouponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_coupon_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCouponNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.txt_coupon_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String txtCouponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.amt_used
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.dat_apply
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datApply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_coupon_usedno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCouponUsedno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.ctr_effect_rate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal ctrEffectRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_icon_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIconNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_amount_xref.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_id
     *
     * @return the value of tms_ivmt_amount_xref.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_id
     *
     * @param codId the value for tms_ivmt_amount_xref.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_ivmt_no
     *
     * @return the value of tms_ivmt_amount_xref.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIvmtNo() {
        return codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_ivmt_no
     *
     * @param codIvmtNo the value for tms_ivmt_amount_xref.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtNo(String codIvmtNo) {
        this.codIvmtNo = codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_coupon_type
     *
     * @return the value of tms_ivmt_amount_xref.cod_coupon_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodCouponType() {
        return codCouponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_coupon_type
     *
     * @param codCouponType the value for tms_ivmt_amount_xref.cod_coupon_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCouponType(Integer codCouponType) {
        this.codCouponType = codCouponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_coupon_no
     *
     * @return the value of tms_ivmt_amount_xref.cod_coupon_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCouponNo() {
        return codCouponNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_coupon_no
     *
     * @param codCouponNo the value for tms_ivmt_amount_xref.cod_coupon_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCouponNo(String codCouponNo) {
        this.codCouponNo = codCouponNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.txt_coupon_name
     *
     * @return the value of tms_ivmt_amount_xref.txt_coupon_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getTxtCouponName() {
        return txtCouponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.txt_coupon_name
     *
     * @param txtCouponName the value for tms_ivmt_amount_xref.txt_coupon_name
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setTxtCouponName(String txtCouponName) {
        this.txtCouponName = txtCouponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.amt_used
     *
     * @return the value of tms_ivmt_amount_xref.amt_used
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtUsed() {
        return amtUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.amt_used
     *
     * @param amtUsed the value for tms_ivmt_amount_xref.amt_used
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtUsed(BigDecimal amtUsed) {
        this.amtUsed = amtUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.dat_apply
     *
     * @return the value of tms_ivmt_amount_xref.dat_apply
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatApply() {
        return datApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.dat_apply
     *
     * @param datApply the value for tms_ivmt_amount_xref.dat_apply
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatApply(Date datApply) {
        this.datApply = datApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_coupon_usedno
     *
     * @return the value of tms_ivmt_amount_xref.cod_coupon_usedno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCouponUsedno() {
        return codCouponUsedno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_coupon_usedno
     *
     * @param codCouponUsedno the value for tms_ivmt_amount_xref.cod_coupon_usedno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCouponUsedno(String codCouponUsedno) {
        this.codCouponUsedno = codCouponUsedno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.ctr_effect_rate
     *
     * @return the value of tms_ivmt_amount_xref.ctr_effect_rate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCtrEffectRate() {
        return ctrEffectRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.ctr_effect_rate
     *
     * @param ctrEffectRate the value for tms_ivmt_amount_xref.ctr_effect_rate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrEffectRate(BigDecimal ctrEffectRate) {
        this.ctrEffectRate = ctrEffectRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_icon_no
     *
     * @return the value of tms_ivmt_amount_xref.cod_icon_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIconNo() {
        return codIconNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_icon_no
     *
     * @param codIconNo the value for tms_ivmt_amount_xref.cod_icon_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIconNo(String codIconNo) {
        this.codIconNo = codIconNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.dat_create
     *
     * @return the value of tms_ivmt_amount_xref.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.dat_create
     *
     * @param datCreate the value for tms_ivmt_amount_xref.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_create_user
     *
     * @return the value of tms_ivmt_amount_xref.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_create_user
     *
     * @param codCreateUser the value for tms_ivmt_amount_xref.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_create_org
     *
     * @return the value of tms_ivmt_amount_xref.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_create_org
     *
     * @param codCreateOrg the value for tms_ivmt_amount_xref.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.dat_modify
     *
     * @return the value of tms_ivmt_amount_xref.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.dat_modify
     *
     * @param datModify the value for tms_ivmt_amount_xref.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_modify_user
     *
     * @return the value of tms_ivmt_amount_xref.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_modify_user
     *
     * @param codModifyUser the value for tms_ivmt_amount_xref.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.cod_modify_org
     *
     * @return the value of tms_ivmt_amount_xref.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.cod_modify_org
     *
     * @param codModifyOrg the value for tms_ivmt_amount_xref.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_amount_xref.ctr_update_srlno
     *
     * @return the value of tms_ivmt_amount_xref.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_amount_xref.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_ivmt_amount_xref.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}