package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsIvmtProfitEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIvmtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_ivmt_propotion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal codIvmtPropotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_ivmt_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codIvmtUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.amt_ivmt
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtIvmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_profit_class
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProfitClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.amt_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.amt_profit_coupon
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfitCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_profit_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProfitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.dat_comp_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCompStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.dat_comp_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCompEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_profit.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_id
     *
     * @return the value of tms_ivmt_profit.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_id
     *
     * @param codId the value for tms_ivmt_profit.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_ivmt_no
     *
     * @return the value of tms_ivmt_profit.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIvmtNo() {
        return codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_ivmt_no
     *
     * @param codIvmtNo the value for tms_ivmt_profit.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtNo(String codIvmtNo) {
        this.codIvmtNo = codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_acct_no
     *
     * @return the value of tms_ivmt_profit.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodAcctNo() {
        return codAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_acct_no
     *
     * @param codAcctNo the value for tms_ivmt_profit.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAcctNo(String codAcctNo) {
        this.codAcctNo = codAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_cust_id
     *
     * @return the value of tms_ivmt_profit.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCustId() {
        return codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_cust_id
     *
     * @param codCustId the value for tms_ivmt_profit.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCustId(String codCustId) {
        this.codCustId = codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_prod_unit
     *
     * @return the value of tms_ivmt_profit.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdUnit() {
        return codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_prod_unit
     *
     * @param codProdUnit the value for tms_ivmt_profit.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdUnit(Integer codProdUnit) {
        this.codProdUnit = codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_ivmt_propotion
     *
     * @return the value of tms_ivmt_profit.cod_ivmt_propotion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCodIvmtPropotion() {
        return codIvmtPropotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_ivmt_propotion
     *
     * @param codIvmtPropotion the value for tms_ivmt_profit.cod_ivmt_propotion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtPropotion(BigDecimal codIvmtPropotion) {
        this.codIvmtPropotion = codIvmtPropotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_ivmt_unit
     *
     * @return the value of tms_ivmt_profit.cod_ivmt_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodIvmtUnit() {
        return codIvmtUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_ivmt_unit
     *
     * @param codIvmtUnit the value for tms_ivmt_profit.cod_ivmt_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtUnit(Integer codIvmtUnit) {
        this.codIvmtUnit = codIvmtUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.amt_ivmt
     *
     * @return the value of tms_ivmt_profit.amt_ivmt
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtIvmt() {
        return amtIvmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.amt_ivmt
     *
     * @param amtIvmt the value for tms_ivmt_profit.amt_ivmt
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtIvmt(BigDecimal amtIvmt) {
        this.amtIvmt = amtIvmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_profit_class
     *
     * @return the value of tms_ivmt_profit.cod_profit_class
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProfitClass() {
        return codProfitClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_profit_class
     *
     * @param codProfitClass the value for tms_ivmt_profit.cod_profit_class
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProfitClass(String codProfitClass) {
        this.codProfitClass = codProfitClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.amt_profit
     *
     * @return the value of tms_ivmt_profit.amt_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfit() {
        return amtProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.amt_profit
     *
     * @param amtProfit the value for tms_ivmt_profit.amt_profit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfit(BigDecimal amtProfit) {
        this.amtProfit = amtProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.amt_profit_coupon
     *
     * @return the value of tms_ivmt_profit.amt_profit_coupon
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfitCoupon() {
        return amtProfitCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.amt_profit_coupon
     *
     * @param amtProfitCoupon the value for tms_ivmt_profit.amt_profit_coupon
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfitCoupon(BigDecimal amtProfitCoupon) {
        this.amtProfitCoupon = amtProfitCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_profit_type
     *
     * @return the value of tms_ivmt_profit.cod_profit_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProfitType() {
        return codProfitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_profit_type
     *
     * @param codProfitType the value for tms_ivmt_profit.cod_profit_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProfitType(Integer codProfitType) {
        this.codProfitType = codProfitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.dat_comp_start
     *
     * @return the value of tms_ivmt_profit.dat_comp_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCompStart() {
        return datCompStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.dat_comp_start
     *
     * @param datCompStart the value for tms_ivmt_profit.dat_comp_start
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCompStart(Date datCompStart) {
        this.datCompStart = datCompStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.dat_comp_end
     *
     * @return the value of tms_ivmt_profit.dat_comp_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCompEnd() {
        return datCompEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.dat_comp_end
     *
     * @param datCompEnd the value for tms_ivmt_profit.dat_comp_end
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCompEnd(Date datCompEnd) {
        this.datCompEnd = datCompEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.dat_create
     *
     * @return the value of tms_ivmt_profit.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.dat_create
     *
     * @param datCreate the value for tms_ivmt_profit.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_create_user
     *
     * @return the value of tms_ivmt_profit.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_create_user
     *
     * @param codCreateUser the value for tms_ivmt_profit.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_create_org
     *
     * @return the value of tms_ivmt_profit.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_create_org
     *
     * @param codCreateOrg the value for tms_ivmt_profit.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.dat_modify
     *
     * @return the value of tms_ivmt_profit.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.dat_modify
     *
     * @param datModify the value for tms_ivmt_profit.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_modify_user
     *
     * @return the value of tms_ivmt_profit.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_modify_user
     *
     * @param codModifyUser the value for tms_ivmt_profit.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.cod_modify_org
     *
     * @return the value of tms_ivmt_profit.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.cod_modify_org
     *
     * @param codModifyOrg the value for tms_ivmt_profit.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_profit.ctr_update_srlno
     *
     * @return the value of tms_ivmt_profit.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_profit.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_ivmt_profit.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}