package com.penging.tms.common.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmsIvmtMastHistEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Long codId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codIvmtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_ivmt_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codIvmtType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codProdUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_ivmt_propotion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal codIvmtPropotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_ivmt_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codIvmtUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_distribution
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtDistribution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_ivmt_total
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtIvmtTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_ivmt_principal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtIvmtPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_receive_principal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtReceivePrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_profit_expect
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfitExpect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_total_estimate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtTotalEstimate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_profit_actual
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfitActual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_profit_additional
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfitAdditional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_service_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtServiceCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_profit_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfitAdjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date amtAdjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_profit_recover
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtProfitRecover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_sum_extra_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtSumExtraSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_rat_sum_extra_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtRatSumExtraSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_transfer
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtTransfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.amt_trade
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private BigDecimal amtTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.dat_ivmt
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datIvmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_trsf_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codTrsfPortion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_trade_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codTradePortion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_trsf_count
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codTrsfCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_freeze_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer codFreezeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.dat_calculation
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCalculation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.dat_distribution
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datDistribution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_channel_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_user_ref
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codUserRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_txn_ref
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codTxnRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codCreateOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Date datModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private String codModifyOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tms_ivmt_mast_hist.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    private Integer ctrUpdateSrlno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_id
     *
     * @return the value of tms_ivmt_mast_hist.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Long getCodId() {
        return codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_id
     *
     * @param codId the value for tms_ivmt_mast_hist.cod_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodId(Long codId) {
        this.codId = codId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_ivmt_no
     *
     * @return the value of tms_ivmt_mast_hist.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodIvmtNo() {
        return codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_ivmt_no
     *
     * @param codIvmtNo the value for tms_ivmt_mast_hist.cod_ivmt_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtNo(String codIvmtNo) {
        this.codIvmtNo = codIvmtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_prod_no
     *
     * @return the value of tms_ivmt_mast_hist.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodProdNo() {
        return codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_prod_no
     *
     * @param codProdNo the value for tms_ivmt_mast_hist.cod_prod_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdNo(String codProdNo) {
        this.codProdNo = codProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_ivmt_type
     *
     * @return the value of tms_ivmt_mast_hist.cod_ivmt_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodIvmtType() {
        return codIvmtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_ivmt_type
     *
     * @param codIvmtType the value for tms_ivmt_mast_hist.cod_ivmt_type
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtType(Integer codIvmtType) {
        this.codIvmtType = codIvmtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_prod_unit
     *
     * @return the value of tms_ivmt_mast_hist.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodProdUnit() {
        return codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_prod_unit
     *
     * @param codProdUnit the value for tms_ivmt_mast_hist.cod_prod_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodProdUnit(Integer codProdUnit) {
        this.codProdUnit = codProdUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_ivmt_propotion
     *
     * @return the value of tms_ivmt_mast_hist.cod_ivmt_propotion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getCodIvmtPropotion() {
        return codIvmtPropotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_ivmt_propotion
     *
     * @param codIvmtPropotion the value for tms_ivmt_mast_hist.cod_ivmt_propotion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtPropotion(BigDecimal codIvmtPropotion) {
        this.codIvmtPropotion = codIvmtPropotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_ivmt_unit
     *
     * @return the value of tms_ivmt_mast_hist.cod_ivmt_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodIvmtUnit() {
        return codIvmtUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_ivmt_unit
     *
     * @param codIvmtUnit the value for tms_ivmt_mast_hist.cod_ivmt_unit
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodIvmtUnit(Integer codIvmtUnit) {
        this.codIvmtUnit = codIvmtUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_distribution
     *
     * @return the value of tms_ivmt_mast_hist.amt_distribution
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtDistribution() {
        return amtDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_distribution
     *
     * @param amtDistribution the value for tms_ivmt_mast_hist.amt_distribution
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtDistribution(BigDecimal amtDistribution) {
        this.amtDistribution = amtDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_ivmt_total
     *
     * @return the value of tms_ivmt_mast_hist.amt_ivmt_total
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtIvmtTotal() {
        return amtIvmtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_ivmt_total
     *
     * @param amtIvmtTotal the value for tms_ivmt_mast_hist.amt_ivmt_total
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtIvmtTotal(BigDecimal amtIvmtTotal) {
        this.amtIvmtTotal = amtIvmtTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_ivmt_principal
     *
     * @return the value of tms_ivmt_mast_hist.amt_ivmt_principal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtIvmtPrincipal() {
        return amtIvmtPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_ivmt_principal
     *
     * @param amtIvmtPrincipal the value for tms_ivmt_mast_hist.amt_ivmt_principal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtIvmtPrincipal(BigDecimal amtIvmtPrincipal) {
        this.amtIvmtPrincipal = amtIvmtPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_receive_principal
     *
     * @return the value of tms_ivmt_mast_hist.amt_receive_principal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtReceivePrincipal() {
        return amtReceivePrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_receive_principal
     *
     * @param amtReceivePrincipal the value for tms_ivmt_mast_hist.amt_receive_principal
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtReceivePrincipal(BigDecimal amtReceivePrincipal) {
        this.amtReceivePrincipal = amtReceivePrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_profit_expect
     *
     * @return the value of tms_ivmt_mast_hist.amt_profit_expect
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfitExpect() {
        return amtProfitExpect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_profit_expect
     *
     * @param amtProfitExpect the value for tms_ivmt_mast_hist.amt_profit_expect
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfitExpect(BigDecimal amtProfitExpect) {
        this.amtProfitExpect = amtProfitExpect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_total_estimate
     *
     * @return the value of tms_ivmt_mast_hist.amt_total_estimate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtTotalEstimate() {
        return amtTotalEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_total_estimate
     *
     * @param amtTotalEstimate the value for tms_ivmt_mast_hist.amt_total_estimate
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtTotalEstimate(BigDecimal amtTotalEstimate) {
        this.amtTotalEstimate = amtTotalEstimate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_profit_actual
     *
     * @return the value of tms_ivmt_mast_hist.amt_profit_actual
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfitActual() {
        return amtProfitActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_profit_actual
     *
     * @param amtProfitActual the value for tms_ivmt_mast_hist.amt_profit_actual
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfitActual(BigDecimal amtProfitActual) {
        this.amtProfitActual = amtProfitActual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_profit_additional
     *
     * @return the value of tms_ivmt_mast_hist.amt_profit_additional
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfitAdditional() {
        return amtProfitAdditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_profit_additional
     *
     * @param amtProfitAdditional the value for tms_ivmt_mast_hist.amt_profit_additional
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfitAdditional(BigDecimal amtProfitAdditional) {
        this.amtProfitAdditional = amtProfitAdditional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_service_charge
     *
     * @return the value of tms_ivmt_mast_hist.amt_service_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtServiceCharge() {
        return amtServiceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_service_charge
     *
     * @param amtServiceCharge the value for tms_ivmt_mast_hist.amt_service_charge
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtServiceCharge(BigDecimal amtServiceCharge) {
        this.amtServiceCharge = amtServiceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_profit_adjust
     *
     * @return the value of tms_ivmt_mast_hist.amt_profit_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfitAdjust() {
        return amtProfitAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_profit_adjust
     *
     * @param amtProfitAdjust the value for tms_ivmt_mast_hist.amt_profit_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfitAdjust(BigDecimal amtProfitAdjust) {
        this.amtProfitAdjust = amtProfitAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_adjust
     *
     * @return the value of tms_ivmt_mast_hist.amt_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getAmtAdjust() {
        return amtAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_adjust
     *
     * @param amtAdjust the value for tms_ivmt_mast_hist.amt_adjust
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtAdjust(Date amtAdjust) {
        this.amtAdjust = amtAdjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_profit_recover
     *
     * @return the value of tms_ivmt_mast_hist.amt_profit_recover
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtProfitRecover() {
        return amtProfitRecover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_profit_recover
     *
     * @param amtProfitRecover the value for tms_ivmt_mast_hist.amt_profit_recover
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtProfitRecover(BigDecimal amtProfitRecover) {
        this.amtProfitRecover = amtProfitRecover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_sum_extra_source
     *
     * @return the value of tms_ivmt_mast_hist.amt_sum_extra_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtSumExtraSource() {
        return amtSumExtraSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_sum_extra_source
     *
     * @param amtSumExtraSource the value for tms_ivmt_mast_hist.amt_sum_extra_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtSumExtraSource(BigDecimal amtSumExtraSource) {
        this.amtSumExtraSource = amtSumExtraSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_rat_sum_extra_source
     *
     * @return the value of tms_ivmt_mast_hist.amt_rat_sum_extra_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtRatSumExtraSource() {
        return amtRatSumExtraSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_rat_sum_extra_source
     *
     * @param amtRatSumExtraSource the value for tms_ivmt_mast_hist.amt_rat_sum_extra_source
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtRatSumExtraSource(BigDecimal amtRatSumExtraSource) {
        this.amtRatSumExtraSource = amtRatSumExtraSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_transfer
     *
     * @return the value of tms_ivmt_mast_hist.amt_transfer
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtTransfer() {
        return amtTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_transfer
     *
     * @param amtTransfer the value for tms_ivmt_mast_hist.amt_transfer
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtTransfer(BigDecimal amtTransfer) {
        this.amtTransfer = amtTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.amt_trade
     *
     * @return the value of tms_ivmt_mast_hist.amt_trade
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public BigDecimal getAmtTrade() {
        return amtTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.amt_trade
     *
     * @param amtTrade the value for tms_ivmt_mast_hist.amt_trade
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setAmtTrade(BigDecimal amtTrade) {
        this.amtTrade = amtTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_cust_id
     *
     * @return the value of tms_ivmt_mast_hist.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCustId() {
        return codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_cust_id
     *
     * @param codCustId the value for tms_ivmt_mast_hist.cod_cust_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCustId(String codCustId) {
        this.codCustId = codCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_acct_no
     *
     * @return the value of tms_ivmt_mast_hist.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodAcctNo() {
        return codAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_acct_no
     *
     * @param codAcctNo the value for tms_ivmt_mast_hist.cod_acct_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodAcctNo(String codAcctNo) {
        this.codAcctNo = codAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.dat_ivmt
     *
     * @return the value of tms_ivmt_mast_hist.dat_ivmt
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatIvmt() {
        return datIvmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.dat_ivmt
     *
     * @param datIvmt the value for tms_ivmt_mast_hist.dat_ivmt
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatIvmt(Date datIvmt) {
        this.datIvmt = datIvmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_trsf_portion
     *
     * @return the value of tms_ivmt_mast_hist.cod_trsf_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodTrsfPortion() {
        return codTrsfPortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_trsf_portion
     *
     * @param codTrsfPortion the value for tms_ivmt_mast_hist.cod_trsf_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodTrsfPortion(Integer codTrsfPortion) {
        this.codTrsfPortion = codTrsfPortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_trade_portion
     *
     * @return the value of tms_ivmt_mast_hist.cod_trade_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodTradePortion() {
        return codTradePortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_trade_portion
     *
     * @param codTradePortion the value for tms_ivmt_mast_hist.cod_trade_portion
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodTradePortion(Integer codTradePortion) {
        this.codTradePortion = codTradePortion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_trsf_count
     *
     * @return the value of tms_ivmt_mast_hist.cod_trsf_count
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodTrsfCount() {
        return codTrsfCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_trsf_count
     *
     * @param codTrsfCount the value for tms_ivmt_mast_hist.cod_trsf_count
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodTrsfCount(Integer codTrsfCount) {
        this.codTrsfCount = codTrsfCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_freeze_no
     *
     * @return the value of tms_ivmt_mast_hist.cod_freeze_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCodFreezeNo() {
        return codFreezeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_freeze_no
     *
     * @param codFreezeNo the value for tms_ivmt_mast_hist.cod_freeze_no
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodFreezeNo(Integer codFreezeNo) {
        this.codFreezeNo = codFreezeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.dat_calculation
     *
     * @return the value of tms_ivmt_mast_hist.dat_calculation
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCalculation() {
        return datCalculation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.dat_calculation
     *
     * @param datCalculation the value for tms_ivmt_mast_hist.dat_calculation
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCalculation(Date datCalculation) {
        this.datCalculation = datCalculation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.dat_distribution
     *
     * @return the value of tms_ivmt_mast_hist.dat_distribution
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatDistribution() {
        return datDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.dat_distribution
     *
     * @param datDistribution the value for tms_ivmt_mast_hist.dat_distribution
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatDistribution(Date datDistribution) {
        this.datDistribution = datDistribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_channel_id
     *
     * @return the value of tms_ivmt_mast_hist.cod_channel_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodChannelId() {
        return codChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_channel_id
     *
     * @param codChannelId the value for tms_ivmt_mast_hist.cod_channel_id
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodChannelId(String codChannelId) {
        this.codChannelId = codChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_user_ref
     *
     * @return the value of tms_ivmt_mast_hist.cod_user_ref
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodUserRef() {
        return codUserRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_user_ref
     *
     * @param codUserRef the value for tms_ivmt_mast_hist.cod_user_ref
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodUserRef(String codUserRef) {
        this.codUserRef = codUserRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_txn_ref
     *
     * @return the value of tms_ivmt_mast_hist.cod_txn_ref
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodTxnRef() {
        return codTxnRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_txn_ref
     *
     * @param codTxnRef the value for tms_ivmt_mast_hist.cod_txn_ref
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodTxnRef(String codTxnRef) {
        this.codTxnRef = codTxnRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.dat_create
     *
     * @return the value of tms_ivmt_mast_hist.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatCreate() {
        return datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.dat_create
     *
     * @param datCreate the value for tms_ivmt_mast_hist.dat_create
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatCreate(Date datCreate) {
        this.datCreate = datCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_create_user
     *
     * @return the value of tms_ivmt_mast_hist.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateUser() {
        return codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_create_user
     *
     * @param codCreateUser the value for tms_ivmt_mast_hist.cod_create_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateUser(String codCreateUser) {
        this.codCreateUser = codCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_create_org
     *
     * @return the value of tms_ivmt_mast_hist.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodCreateOrg() {
        return codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_create_org
     *
     * @param codCreateOrg the value for tms_ivmt_mast_hist.cod_create_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodCreateOrg(String codCreateOrg) {
        this.codCreateOrg = codCreateOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.dat_modify
     *
     * @return the value of tms_ivmt_mast_hist.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Date getDatModify() {
        return datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.dat_modify
     *
     * @param datModify the value for tms_ivmt_mast_hist.dat_modify
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setDatModify(Date datModify) {
        this.datModify = datModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_modify_user
     *
     * @return the value of tms_ivmt_mast_hist.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyUser() {
        return codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_modify_user
     *
     * @param codModifyUser the value for tms_ivmt_mast_hist.cod_modify_user
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyUser(String codModifyUser) {
        this.codModifyUser = codModifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.cod_modify_org
     *
     * @return the value of tms_ivmt_mast_hist.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public String getCodModifyOrg() {
        return codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.cod_modify_org
     *
     * @param codModifyOrg the value for tms_ivmt_mast_hist.cod_modify_org
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCodModifyOrg(String codModifyOrg) {
        this.codModifyOrg = codModifyOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tms_ivmt_mast_hist.ctr_update_srlno
     *
     * @return the value of tms_ivmt_mast_hist.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public Integer getCtrUpdateSrlno() {
        return ctrUpdateSrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tms_ivmt_mast_hist.ctr_update_srlno
     *
     * @param ctrUpdateSrlno the value for tms_ivmt_mast_hist.ctr_update_srlno
     *
     * @mbggenerated Fri Jan 29 18:19:53 CST 2016
     */
    public void setCtrUpdateSrlno(Integer ctrUpdateSrlno) {
        this.ctrUpdateSrlno = ctrUpdateSrlno;
    }
}